- BetterGenshinImpact/Model/HotKey.cs
fix #4 
```
修复删除已配置的快捷键为None，重新启动软件时的异常
```
> 修复删除已配置的快捷键为None，重新启动软件时的异常

- BetterGenshinImpact.Test/HsvTestWindow.cs
- BetterGenshinImpact.Test/MainWindow.xaml.cs
- BetterGenshinImpact/BetterGenshinImpact.csproj
- BetterGenshinImpact/Core/Recognition/OpenCv/OpenCvCommonHelper.cs
- BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
- BetterGenshinImpact/GameTask/AutoSkip/AutoSkipTrigger.cs
- BetterGenshinImpact/GameTask/Common/MiniMap/CameraOrientation.cs
- BetterGenshinImpact/GameTask/Common/MiniMap/CharacterOrientation.cs
- BetterGenshinImpact/GameTask/Common/MiniMap/MiniMap.cs
- BetterGenshinImpact/GameTask/Common/TaskControl.cs
- BetterGenshinImpact/GameTask/Placeholder/PlaceholderTrigger.cs
- BetterGenshinImpact/Helpers/StringUtils.cs
- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
- BetterGenshinImpact/ViewModel/Pages/HomePageViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
第一版，单轮秘境基本完成。战斗模块还有较大问题，需要优化。、
剩下的就是多轮次的兼容和领取奖励操作了
> first version for auto domain

- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingConfig.cs
- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTrigger.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/BigFishType.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/FishType.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/Fishpond.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/OneFish.cs
- BetterGenshinImpact/GameTask/AutoFishing/RodInput.cs
- BetterGenshinImpact/GameTask/AutoFishing/RodNet.cs
- BetterGenshinImpact/View/Pages/TriggerSettingsPage.xaml
- README.md
感谢 @myHuTao-qwq 的 https://github.com/myHuTao-qwq/HutaoFisher 项目！
1. 使用了 HutaoFisher 的数据集进行重新训练新的识别模型
2. 使用了 HutaoFisher 的抛竿算法替换原有笨拙的抛竿方式
> 来自 HutaoFisher 更好的识别模型以及极为优秀的抛竿算法

- BetterGenshinImpact/GameTask/TaskTriggerDispatcher.cs
- BetterGenshinImpact/ViewModel/Pages/HomePageViewModel.cs
> 检测游戏退出时停止任务并更新UI

- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
> 打开脚本列表时刷新文件列表

- BetterGenshinImpact/App.xaml
- BetterGenshinImpact/View/Converters/BooleanToVisibilityRevertConverter.cs
- BetterGenshinImpact/View/MaskWindow.xaml
- BetterGenshinImpact/View/Pages/HomePage.xaml
- BetterGenshinImpact/ViewModel/MaskWindowViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/HomePageViewModel.cs
> Use converter to optimize binding

- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
大哥merge的有点快
#294 漏了自动秘境的下拉菜单
然后我刚刚在想是不是用event trigger比较好
孩子想学c#了，来找点简单的做做
> 修复#294中漏掉的下拉菜单

- BetterGenshinImpact/BetterGenshinImpact.csproj
- BetterGenshinImpact/View/MainWindow.xaml
- BetterGenshinImpact/View/MainWindow.xaml.cs
- BetterGenshinImpact/ViewModel/MainWindowViewModel.cs
#109
有两个想法
1. 添加单独的“最小化到托盘”按钮
2. 添加一个设置，最小化时隐藏至托盘
这个是第一种，长这样
没搞懂怎么用binding实现Activate()和用xaml做NotifyIcon
> 添加最小化到托盘的按钮

- BetterGenshinImpact/Core/Config/MaskWindowConfig.cs
- BetterGenshinImpact/Model/StatusItem.cs
- BetterGenshinImpact/View/MaskWindow.xaml
- BetterGenshinImpact/View/MaskWindow.xaml.cs
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
- BetterGenshinImpact/ViewModel/MaskWindowViewModel.cs
试着做了个状态指示
shit code就是chatgpt教的
> 在遮盖窗口中添加状态指示

- BetterGenshinImpact/View/MainWindow.xaml.cs
> 启动时将窗口置于前台

- BetterGenshinImpact/Core/Config/CommonConfig.cs
- BetterGenshinImpact/View/MainWindow.xaml
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
- BetterGenshinImpact/ViewModel/MainWindowViewModel.cs
> 通用设置里增加“退出时最小化到托盘”选项

- BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
- BetterGenshinImpact/GameTask/AutoFight/Assets/AutoFightAssets.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightContext.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
- BetterGenshinImpact/GameTask/AutoFishing/Assets/AutoFishingAssets.cs
- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTrigger.cs
- BetterGenshinImpact/GameTask/AutoGeniusInvokation/Assets/AutoGeniusInvokationAssets.cs
- BetterGenshinImpact/GameTask/AutoGeniusInvokation/GeniusInvokationControl.cs
- BetterGenshinImpact/GameTask/AutoPick/Assets/AutoPickAssets.cs
- BetterGenshinImpact/GameTask/AutoPick/AutoPickTrigger.cs
- BetterGenshinImpact/GameTask/AutoSkip/Assets/AutoSkipAssets.cs
- BetterGenshinImpact/GameTask/AutoSkip/AutoSkipTrigger.cs
- BetterGenshinImpact/GameTask/AutoWood/Assets/AutoWoodAssets.cs
- BetterGenshinImpact/GameTask/AutoWood/AutoWoodTask.cs
- BetterGenshinImpact/GameTask/Common/Element/Assets/ElementAssets.cs
- BetterGenshinImpact/GameTask/Model/BaseAssets.cs
- BetterGenshinImpact/GameTask/QuickSereniteaPot/Assets/QuickSereniteaPotAssets.cs
- BetterGenshinImpact/GameTask/QuickSereniteaPot/QuickSereniteaPotTask.cs
- BetterGenshinImpact/GameTask/QuickTeleport/Assets/QuickTeleportAssets.cs
- BetterGenshinImpact/GameTask/QuickTeleport/QuickTeleportTrigger.cs
所有存储识别素材体的类都继承单例，方便在不同中的任务中直接调用素材
```C#
public class Singleton<T> where T : class
{
// 使用Lazy<T>确保线程安全的延迟初始化
private static readonly Lazy<T> _instance = new(() => CreateInstanceOfT()!, isThreadSafe: true);
public static T Instance => _instance.Value;
// 保护的构造函数，防止直接实例化
protected Singleton()
{
}
private static T? CreateInstanceOfT()
{
return Activator.CreateInstance(typeof(T), true) as T;
}
}
```
> All assets to singleton

- BetterGenshinImpact.Test/BetterGenshinImpact.Test.csproj
- BetterGenshinImpact.Test/MainWindow.xaml.cs
- BetterGenshinImpact.Win32/BetterGenshinImpact.Win32.csproj
- BetterGenshinImpact/BetterGenshinImpact.csproj
- BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTrigger.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/Fishpond.cs
- BetterGenshinImpact/Helpers/ObjectUtils.cs
- BetterGenshinImpact/Properties/PublishProfiles/FolderProfile.pubxml
- BetterGenshinImpact/View/MaskWindow.xaml
- BetterGenshinImpact/View/Pages/KeyMouseRecordPage.xaml
- Fischless.GameCapture/BitBlt/BitBltCapture.cs
- Fischless.GameCapture/Fischless.GameCapture.csproj
- Fischless.HotkeyCapture/Fischless.HotkeyCapture.csproj
- Fischless.KeyboardCapture/Fischless.KeyboardCapture.csproj
- Fischless.WindowsInput/Fischless.WindowsInput.csproj
- Vision.WindowCapture.Test/Vision.WindowCapture.Test.csproj
- Vision.WindowCapture/Vision.WindowCapture.csproj
> update to .net8

- BetterGenshinImpact.Test/BetterGenshinImpact.Test.csproj
- BetterGenshinImpact.Win32/BetterGenshinImpact.Win32.csproj
- BetterGenshinImpact/BetterGenshinImpact.csproj
- BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
- Build/MicaSetup/MicaSetup.Uninst.csproj
- Build/MicaSetup/MicaSetup.csproj
- Fischless.GameCapture/Fischless.GameCapture.csproj
- Fischless.HotkeyCapture/Fischless.HotkeyCapture.csproj
- Fischless.KeyboardCapture/Fischless.KeyboardCapture.csproj
- Vision.WindowCapture.Test/Vision.WindowCapture.Test.csproj
- Vision.WindowCapture/Vision.WindowCapture.csproj
feat: 优化autopath MoveTo逻辑
- 增加使用角色技能逻辑
- 抽象移动逻辑，方便扩展
- 修复waypoint移动异常时，无法正确跳过问题
> feat: 优化autopath MoveTo逻辑

- BetterGenshinImpact/GameTask/AutoPathing/Handler/PickAroundHandler.cs
> 添加PickAround实现（浅测试）

- BetterGenshinImpact/View/Pages/ScriptControlPage.xaml
> Refine Script Control Page

- BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
- BetterGenshinImpact/View/Pages/HomePage.xaml
> 降低鼠标后半部分移动速度，以避免惯性，作为补偿前面一半的速度变快了。

- BetterGenshinImpact/Core/Config/PathingPartyConfig.cs
- BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightConfig.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/AutoFightHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/CombatScriptHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/ElementalCollectHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/ElementalSkillHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/IActionHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/MiningHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/NahidaCollectHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/NormalAttackHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/PickAroundHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/UpDownGrabLeaf.cs
- BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
- BetterGenshinImpact/GameTask/Common/TaskControl.cs
- BetterGenshinImpact/View/Pages/ScriptControlPage.xaml
- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
- BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml
- BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml.cs
- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/View/AutoFightViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/View/ScriptGroupConfigViewModel.cs
路径追踪支持战斗配置功能。自动战斗支持检查结束偏色调整（与队伍无关，只有在独立任务处的自动战斗中设置），调度器增加清空功能。暂停增加按下键清除操作。
> 路径追踪支持战斗配置

- BetterGenshinImpact/GameTask/LogParse/LogParse.cs
> 添加日志分析匹配日志文件带后缀的情况。

- BetterGenshinImpact/Core/Config/AllConfig.cs
- BetterGenshinImpact/GameTask/AutoTrackPath/TpConfig.cs
- BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
- BetterGenshinImpact/View/Pages/TriggerSettingsPage.xaml
> 增加了地图移动的相关参数设置的界面

- BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
> auto pathing: reduce the startup time of `MoveCloseTo`

- BetterGenshinImpact/User/avatar_macro.json
> Update avatar_macro.json  补充新角色；增加玛薇卡跳喷宏，按住极限平地9次跳喷

- BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs
最终效果好不好取决于这个dpi模拟鼠标的倍率在不同机器上差别有多大。反正我试出来我能用。
> feature：恰斯卡重击

- BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs
被代码的三重冗余暗算了……这里真不需要重构吗（
该改动已通过本人测试
> bugfix：自动战斗中切人前解除爬行状态

- BetterGenshinImpact/Core/Script/Dependence/Genshin.cs
- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTask.cs
- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTrigger.cs
- BetterGenshinImpact/GameTask/AutoFishing/BehaviourTreeExtensions.cs
- BetterGenshinImpact/GameTask/AutoFishing/Behaviours.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/Fishpond.cs
- BetterGenshinImpact/GameTask/AutoPathing/Handler/FishingHandler.cs
- BetterGenshinImpact/GameTask/Model/Area/ImageRegion.cs
- BetterGenshinImpact/GameTask/Model/Area/Region.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ChooseBait.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.FishBite.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.GetFishpond.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ThrowRod.cs
> 给js脚本的genshin.autofishing方法暴露参数 等一波优化

- BetterGenshinImpact/Core/Script/Group/ScriptGroupProject.cs
- BetterGenshinImpact/GameTask/Shell/ShellExecutor.cs
- BetterGenshinImpact/Service/ScriptService.cs
- BetterGenshinImpact/View/Pages/ScriptControlPage.xaml
- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
可以自动重启原神，关闭计算机也不会卡住....
关于安全问题:其实键鼠模拟本来就会带来安全问题，执行命令行的时候没有做成导入而是由用户自己输入，提示也加了警告....
应该不会有人乱搞把（
> 给配置组增加执行shell的功能，可以调用外部程序实现复杂调度

- BetterGenshinImpact/Service/Notifier/EmailNotifier.cs
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
> 新增图片作为email附件发送功能

- BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
- BetterGenshinImpact/GameTask/LogParse/LogParse.cs
- BetterGenshinImpact/Service/Notification/NotificationConfig.cs
- BetterGenshinImpact/Service/Notifier/WebSocketNotifier.cs
- BetterGenshinImpact/Service/Notifier/WebhookNotifier.cs
- README.md
This pull request includes several changes to the notification system in the `BetterGenshinImpact` project, specifically focusing on enhancing the functionality and configuration of different notifiers. The most important changes include updates to the `EmailNotifier`, `WebhookNotifier`, and `NotificationConfig` classes, as well as modifications to the user interface for configuring notifications.
* **Email Notifier Improvements:**
- Refactored the `EmailNotifier` class to ignore SSL certificate validation errors and create a new `SmtpClient` instance for each email sent. This also includes adding support for attaching screenshots to emails. [[1]](diffhunk://#diff-28f2f2d4ce7c21bf6f1862b7cc919192320509e0c63ca4780b2a32b998fe212cR1-R3) …
> webhook添加了sendto发送对象，修复了webhook通知ui显示错误问题，修复了websocket服务端错误关闭链接问题

- BetterGenshinImpact/Service/Notification/NotificationConfig.cs
- BetterGenshinImpact/Service/Notification/NotificationService.cs
- BetterGenshinImpact/Service/Notifier/xxtuiNotifier.cs
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
- BetterGenshinImpact/ViewModel/Pages/CommonSettingsPageViewModel.cs
> 新增xxtui通知方法

- BetterGenshinImpact/ViewModel/Pages/HomePageViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
> 从命令行启动调度器，暂不支持URL(--startGroups 组1 组2 ...)

- BetterGenshinImpact/Service/Notifier/TelegramNotifier.cs
> 修正tg变量正确性，修正tgbotapi端点反代使用

- BetterGenshinImpact/Service/Notification/NotificationService.cs
优化推送逻辑，加入异步推送策略，降低在多开渠道下的瞬间性能负载。
提升推送速度。
提升代码可维护性
> 优化推送逻辑，加入异步推送策略。

- BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs
- BetterGenshinImpact/GameTask/GameTaskManager.cs
- BetterGenshinImpact/GameTask/TaskTriggerDispatcher.cs
倒是还没有测试
但是理论上 AddTimer 的效果和之前相同，不破坏现有脚本执行
加了俩
ClearAllTriggers : 清理所有实时任务
AddTrigger : 加实时任务,不会清理之前的任务
> 添加实时任务,不会清理之前的任务

- BetterGenshinImpact/GameTask/AutoPathing/Handler/MiningHandler.cs
- BetterGenshinImpact/GameTask/AutoPathing/Model/WaypointForTrack.cs
> 增加对WaypointForTrack的DisablePickupAround属性支持，可以关闭挖矿动作的周围拾取

- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml.cs
- BetterGenshinImpact/View/Windows/AboutWindow.xaml
- BetterGenshinImpact/View/Windows/AboutWindow.xaml.cs
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/babalae/better-genshin-impact/pull/1348?shareId=c9a970e7-f705-4c49-8bbf-75bc332fbdef).
> Add About option to settings page

- BetterGenshinImpact/GameTask/AutoFight/Assets/combat_avatar.json
- BetterGenshinImpact/GameTask/AutoTrackPath/Assets/tp.json
- BetterGenshinImpact/GameTask/Common/Job/ExitAndReloginJob.cs
> 自动秘境添加【荒废砌造坞】，仅供临时使用

- BetterGenshinImpact/Core/Config/KeyBindingsConfig.cs
> fix：左Ctrl名称错误

- BetterGenshinImpact/Core/Script/Dependence/LimitedFile.cs
```javascript
const result = file.WriteTextSync(path, content, append);
```
**参数说明：**
- `path`: 文件路径（字符串）
- `content`: 要写入的内容（字符串）
- `append`: 是否追加模式（布尔值，默认为false表示覆盖写入）
**返回值：**
- 布尔值，表示写入是否成功
**示例：**
```javascript
// 覆盖写入
const result1 = file.WriteTextSync("test/example.txt", "这是覆盖写入的内容");
// 追加写入
const result2 = file.WriteTextSync("test/example.txt", "这是追加的内容", true);
```
```javascript
// Promise方式
const result = await file.WriteText(path, content, append);
// 回调方式
await file.WriteText(path, content, callback, append);
```
**参数说明：**
- `path`: 文件路径（字符串）
- `content`: 要写入的内容（字符串）
- `append`: 是否追加模式（布尔值，默认为false表示覆盖写入）
- `callback`: 回调函数，格式为 `function(error, result)`
**返回值：**
- Promise方式：返回Promise<boolean>，表示写入是否成功
- 回调方式：通过回调函数返回结果
**示例：**
Promise方式：
```javascript
(async function() {
// …
```
> js(file): 文件写入支持

- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
暂时只有这个小小的修改，忘了NumberBox的Value和Text俩都要绑定了
> 界面数据绑定漏洞修复

- BetterGenshinImpact/Core/Script/Dependence/LimitedFile.cs
- BetterGenshinImpact/GameTask/AutoGeniusInvokation/GeniusInvokationControl.cs
读取指定文件夹内所有文件的路径（非递归）并返回相对路径
（用于便捷化联机锄地JS的地图追踪设置）
改了个错字
> 添加JS异步目录读取

- BetterGenshinImpact/Core/Script/Dependence/LimitedFile.cs
- BetterGenshinImpact/GameTask/AutoGeniusInvokation/GeniusInvokationControl.cs
原先的文件读取只能读取文件夹内的非文件夹路径，现已改成文件夹和非文件夹路径
添加isFolder判断路径是否为文件夹
> 文件读取支持读取文件夹，添加方法判断路径是否为文件夹

- BetterGenshinImpact/Core/Config/HotKeyConfig.cs
- BetterGenshinImpact/Core/Config/OneDragonFlowConfig.cs
- BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs
- BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs
- BetterGenshinImpact/GameTask/Common/Job/SwitchPartyTask.cs
- BetterGenshinImpact/Model/OneDragonTaskItem.cs
- BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
- BetterGenshinImpact/ViewModel/Pages/HotKeyPageViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/OneDragonFlowViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
1.一条龙菜单增加配置组,每周7天单独配置，增加一条龙快捷方式。
2.自动秘境执行条件，到达秘境向前走的时间加长。
3.切换队伍API，失败重试3次，切换识别不退出任务。
PS:佬们，俺是小白，第一次PR项目，我写的看有没有用，操作不知道对不对，如有错误请指教。
> 一条龙菜单、自动秘境、切换队伍相关修改

- BetterGenshinImpact/GameTask/AutoFight/AutoFightConfig.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs
- BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs
- BetterGenshinImpact/GameTask/Common/Job/ScanPickTask.cs
- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
- BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml
改为边走边找这样更灵活的闭环控制
增加了推理次数，把压力留给推理设备:D
> feat: efficient scan pick

- BetterGenshinImpact/GameTask/AutoPick/AutoPickTrigger.cs
> fix: 修复拾取过程中文字识别错误

- BetterGenshinImpact/GameTask/AutoPathing/Handler/UpDownGrabLeaf.cs
- BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
action_params 支持传入优先向上或者向下寻找，默认优先向上。参数格式为
向上寻找：
```
"action_params": "up"
```
向下寻找：
```
"action_params": "down"
````
当然实际上只要传入不是up的参数都是向下寻找（
测试用例（基础功能测试）：
```json
{
"info": {
"name": "四叶印测试",
"type": "collect",
"author": "秋云",
"version": "",
"description": "",
"bgiVersion": "0.42.3"
},
"positions": [
{
"id": 1,
"x": 2401.09,
"y": 149.37,
"action": "",
"move_mode": "walk",
"type": "teleport"
},
{
"id": 2,
"x": 2396.68,
"y": 161.03,
"action": "",
"move_mode": "walk",
"type": "path"
},
{
"id": 3,
"x": 2382.23,
"y": 178.46,
"type": "path",
"move_mode": "walk",
"action": "up_down_grab_leaf",
"action_params": ""
},
{
"id": 4,
"x": 2386.99,
"y": 196.56,
"type": "path",
"move_mode": "walk",
"action": "up_down_grab_leaf",
"action_params": ""
}
]
}
```
测试用例（连续四叶印测试）：
```json
{
"info": {
"name": …
```
> fix: 更高效的四叶印

- BetterGenshinImpact/GameTask/AutoTrackPath/TpConfig.cs
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
> fix #1498 and _mapScaleFactor 添加参数范围限制提示

- BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
一条龙列表空时添加提示“± 鼠标右击添加或删除任务”，按钮优化布局
> 一条龙列表空时添加提示，按钮优化

- BetterGenshinImpact/Core/Recognition/ONNX/BgiYoloPredictor.cs
- BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs
- BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
- BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTask.cs
- BetterGenshinImpact/GameTask/AutoFishing/Behaviours.cs
- BetterGenshinImpact/GameTask/AutoGeniusInvokation/GeniusInvokationControl.cs
- BetterGenshinImpact/GameTask/AutoPathing/Navigation.cs
- BetterGenshinImpact/GameTask/AutoPick/AutoPickTrigger.cs
- BetterGenshinImpact/GameTask/AutoSkip/AutoSkipTrigger.cs
- BetterGenshinImpact/GameTask/AutoSkip/AutoTrackTask.cs
- BetterGenshinImpact/GameTask/AutoSkip/ExpeditionTask.cs
- BetterGenshinImpact/GameTask/AutoTrackPath/PathPointRecorder.cs
- BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
- BetterGenshinImpact/GameTask/Common/Job/GoToCraftingBenchTask.cs
- BetterGenshinImpact/GameTask/Model/Area/GameCaptureRegion.cs
- BetterGenshinImpact/GameTask/Model/Area/ImageRegion.cs
- BetterGenshinImpact/GameTask/Placeholder/PlaceholderTrigger.cs
- BetterGenshinImpact/GameTask/QuickTeleport/QuickTeleportTrigger.cs
- BetterGenshinImpact/Helpers/Extensions/MatExtension.cs
- BetterGenshinImpact/Service/Notification/Model/BaseNotificationData.cs
- BetterGenshinImpact/Service/Notification/NotificationService.cs
- BetterGenshinImpact/Service/Notifier/EmailNotifier.cs
- BetterGenshinImpact/Service/Notifier/FeishuNotifier.cs
- BetterGenshinImpact/Service/Notifier/OneBotNotifier.cs
- BetterGenshinImpact/Service/Notifier/WindowsUwpNotifier.cs
- BetterGenshinImpact/Service/Notifier/WorkWeixinNotifier.cs
- BetterGenshinImpact/View/CaptureTestWindow.xaml.cs
- BetterGenshinImpact/View/Windows/OcrDialog.xaml.cs
可以直接喂给Yolo了，避免反复编码解码。
还影响通知截图、圣遗物OCR测试。
Yolo那边要是接受BGR就好了，或许可以给他们PR个
> 用Image<Rgb24>替换Bitmap

- Fischless.GameCapture/Graphics/Helpers/HdrToSdrShader.cs
> sRGB变换曲线优化

- .github/workflows/publish.yml
只会打包上传到 Run 下面，不影响其它地方（有 repo owner 验证）。
> 允许 forked repo 通过 BetterGI Publish 自行打包。

- BetterGenshinImpact/Service/ApplicationHostService.cs
- BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
- BetterGenshinImpact/ViewModel/Pages/HomePageViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/OneDragonFlowViewModel.cs
使用方法：
```
BetterGI.exe startOneDragon <配置名称>
BetterGI.exe --startOneDragon <配置名称>
```
相关 issue ：
- #1579
- #846
> 支持在命令行启动一条龙参数时选择配置，配置找不到就用界面指定的。

- BetterGenshinImpact/README.md
- BetterGenshinImpact/Service/ApplicationHostService.cs
测试包：https://github.com/zzc-tongji/better-genshin-impact/actions/runs/15033864300
> 修复一个命令行启动的bug。

- BetterGenshinImpact/GameTask/Common/Element/Assets/ElementAssets.cs
- BetterGenshinImpact/GameTask/Common/Job/GoToSereniteaPotTask.cs
- BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
- BetterGenshinImpact/ViewModel/Pages/OneDragonFlowViewModel.cs
任务列表自动保存，删除排序按钮
尘歌壶购买优化，增加购买间隔等待动画结束后再进行下一轮
> 任务列表自动保存，尘歌壶购买优化

- BetterGenshinImpact/GameTask/AutoFishing/RodInput.cs
- BetterGenshinImpact/GameTask/AutoFishing/RodNet.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/RodNetTests.Training.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/RodNetTests.cs
没用的PR又增加了！
召唤 @myHuTao-qwq ！大神来教我~
> 尝试复现RodNet的训练结果

- BetterGenshinImpact/GameTask/AutoArtifactSalvage/AutoArtifactSalvageTask.cs
- BetterGenshinImpact/GameTask/Model/GameUI/GridScreen.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoArtifactSalvageTests/AutoArtifactSalvageTaskTests.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/Model/GameUI/GridScreenTests.cs
> 封装了一个grid界面的操作类

- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
> 根据文件夹删除任务优化

- BetterGenshinImpact/Service/Notifier/TelegramNotifier.cs
> 重构了一下Telegram通知，现在可以发送图片鸟

- BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
> 尘歌壶选择进入方式UI和序号选择UI优化

- BetterGenshinImpact/Core/Script/Dependence/Genshin.cs
- BetterGenshinImpact/Core/Script/Dependence/GlobalMethod.cs
- BetterGenshinImpact/Core/Script/EngineExtend.cs
```js
(async function () {
await genshin.returnMainUi();
var avatars = getAvatars();
for (let i=0; i<avatars.length; i++){
log.info(`第 ${i+1} 个角色为 ${avatars[i]}`);
}
var ori = genshin.getCameraOrientation();
log.info(`角度为：${ori}`);
})();
```
> js: 暴露获取当前小地图角度和当前队伍角色的方法

- BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
- BetterGenshinImpact/GameTask/AutoFight/Script/CombatCommand.cs
> fix: 部分情况下简易策略报错并丢失

- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
1.  解决调度器为空时程序假死问题 #1945
2.  解决了调度器列表未全选时全选按钮仍被选中的问题
> 修复调度器连续执行页面问题

- BetterGenshinImpact/View/Windows/PromptDialog.xaml
- BetterGenshinImpact/View/Windows/PromptDialog.xaml.cs
- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
- BetterGenshinImpact/ViewModel/Pages/TriggerSettingsPageViewModel.cs
优化前VS优化后
**1. JS脚本添加界面**
**2. 地图追踪任务添加界面**
**3. 单行文本框调用页面**
**4. 多行文本框调用页面**
> 优化PromptDialog对话框布局以支持用户自由调整窗口大小

- BetterGenshinImpact/GameTask/AutoWood/Utils/Login3rdParty.cs
- BetterGenshinImpact/GameTask/Common/Job/ExitAndReloginJob.cs
- BetterGenshinImpact/GameTask/GameLoading/GameLoading.cs
初次登录可正常使用，但重登录取消了原本的TaskControl中的sleep，改用Thread.sleep()，可能会对脚本执行产生影响，需要额外考虑
> 修复B服登录与重登陆

- BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
1、重试500毫秒改为1000
2、异常处理不抛出错误，改为继续识别执行，至少可以继续刷本。
> 优化自动秘境进入时序和异常处理逻辑

- BetterGenshinImpact/GameTask/AutoFight/AutoFightSeek.cs
- BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml
1/优化旋转寻找敌人逻辑
2/注释手动导入仓库功能(躁动的氨气要求的)
> 优化旋转寻找敌人逻辑/注释手动导入仓库功能

- BetterGenshinImpact/Core/Config/HardwareAccelerationConfig.cs
- BetterGenshinImpact/Core/Recognition/ONNX/BgiOnnxFactory.cs
- BetterGenshinImpact/Core/Recognition/ONNX/InferenceDeviceType.cs
- BetterGenshinImpact/Core/Recognition/ONNX/ProviderType.cs
- BetterGenshinImpact/View/Pages/View/HardwareAccelerationView.xaml
换成openvino之后cpu占用毫无波澜，而且不像cuda之类的需要复杂的环境配置
nuget包我没有动 需要把 Microsoft.ML.OnnxRuntime.DirectML 换成 Intel.ML.OnnxRuntime.OpenVino
> openvino 支持

- BetterGenshinImpact/BetterGenshinImpact.csproj
- Fischless.GameCapture/Fischless.GameCapture.csproj
> update OpenCvSharp4 package versions to 4.11.0.20250507

- BetterGenshinImpact/Core/Config/HardwareAccelerationConfig.cs
- BetterGenshinImpact/Core/Recognition/ONNX/BgiOnnxFactory.cs
- BetterGenshinImpact/View/Pages/View/HardwareAccelerationView.xaml
> 修正ONNX TRT缓存配置，实验性的增加OpenVINO缓存及配置项

- BetterGenshinImpact/Core/Config/HardwareAccelerationConfig.cs
- BetterGenshinImpact/View/Pages/View/HardwareAccelerationView.xaml
> 默认关闭CPU OCR的相关UI文本更新

- BetterGenshinImpact/Core/Config/HardwareAccelerationConfig.cs
> OpenVINO 缓存配置与描述冲突

- BetterGenshinImpact/Service/Notification/NotificationService.cs
- BetterGenshinImpact/Service/Notifier/BarkNotifier.cs
- BetterGenshinImpact/View/Pages/NotificationSettingsPage.xaml
测试图标来自米游社原神主页图标：[1715415528209ys-logo-v2.png](https://bbs-static.miyoushe.com/upload/op_manual_upload/fe/game_list/game_icons/1715415528209ys-logo-v2.png)
> feat: Bark通知设置自定义图标

- BetterGenshinImpact/GameTask/AutoArtifactSalvage/ArtifactAffix.cs
- BetterGenshinImpact/GameTask/AutoArtifactSalvage/ArtifactStat.cs
- BetterGenshinImpact/GameTask/AutoArtifactSalvage/AutoArtifactSalvageConfig.cs
- BetterGenshinImpact/GameTask/AutoArtifactSalvage/AutoArtifactSalvageTask.cs
- BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
- BetterGenshinImpact/View/Windows/OcrDialog.xaml.cs
- BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoArtifactSalvageTests/AutoArtifactSalvageTaskTests.cs
撤掉了临时的正则表达式匹配，换成JS啦，这样就可以满足很多定制需求了，回头甚至还可以整到脚本仓库里？
> 圣遗物分解筛选改用JS

- BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs
- BetterGenshinImpact/GameTask/AutoArtifactSalvage/AutoArtifactSalvageTask.cs
- BetterGenshinImpact/GameTask/AutoEat/AutoEatTask.cs
- BetterGenshinImpact/GameTask/Common/Job/CountInventoryItem.cs
- BetterGenshinImpact/GameTask/GetGridIcons/GetGridIconsTask.cs
- BetterGenshinImpact/GameTask/GetGridIcons/GridIconsAccuracyTestTask.cs
- BetterGenshinImpact/GameTask/ISoloTask.cs
- BetterGenshinImpact/GameTask/Model/GameUI/GridExtensions.cs
- BetterGenshinImpact/GameTask/Model/GameUI/GridScreen.cs
- BetterGenshinImpact/Helpers/ScriptObjectConverter.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoArtifactSalvageTests/AutoArtifactSalvageTaskTests.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/GetGridIconsTests/GetGridIconsTaskTests.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/GetGridIconsTests/GridIconModelFixture.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/GetGridIconsTests/GridIconsAccuracyTestTaskTests.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/Model/GameUI/GridScreenTests.cs
- Test/BetterGenshinImpact.UnitTest/InitCollection.cs
大致是提供一个独立任务调用方法，要求JS传入`背包的分类`、`物品名称`，方法返回值是`数量`。
先帮我review一下，给JS返回值是不是这样合适。。。毕竟影响了所有Dispatcher.RunTask中定义的方法
丹得找人凑一下数据集，我就先数萝卜丸子了。。。
丹的局限是分不了食物的“美味的”这种前缀，因为这种在训练时是作为正样本的。数数普通的材料还是能应付的。
> 给JS调用的背包数数独立任务

- BetterGenshinImpact/View/Pages/ScriptControlPage.xaml
- BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
AI写的，我自己简单断点测了一下没什么问题。如果有地方需要修改的话，麻烦 owner 帮我调整一下
---
> feat: 添加“打开所在目录”菜单项及其命令实现，用于打开脚本文件夹

- BetterGenshinImpact/BetterGenshinImpact.csproj
- BetterGenshinImpact/GameTask/AutoFishing/Behaviours.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/BaitType.cs
- BetterGenshinImpact/GameTask/AutoFishing/Model/BigFishType.cs
- BetterGenshinImpact/GameTask/GetGridIcons/GridIconsAccuracyTestTask.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ChooseBait.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ThrowRod.cs
另外，验证了由于鱼饵识别方案的变化，以下bug已被修复：
Fixes #1560
> 6.0鱼定义和测试用例

- BetterGenshinImpact/GameTask/AutoDomain/Model/ResinStatus.cs
- BetterGenshinImpact/GameTask/Common/Job/SwitchPartyTask.cs
- Test/BetterGenshinImpact.UnitTest/CoreTests/RecognitionTests/OCRTests/PaddleFixture.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoDomainTests/ResinStatusTests.cs
详见 https://pd.qq.com/g/bettergiv1/post/B_c3f9c868ae7b07001441152188356063000X60
> 修复切换队伍列表向下查找时有时会识别不正确的bug

- BetterGenshinImpact/Core/Recognition/OCR/Paddle/Det.cs
- BetterGenshinImpact/Core/Recognition/OCR/Paddle/PaddleOcrService.cs
- BetterGenshinImpact/Core/Recognition/OCR/Paddle/Rec.cs
- Test/BetterGenshinImpact.UnitTest/CoreTests/RecognitionTests/OCRTests/PaddleOcrServiceTests.cs
- Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoDomainTests/ResinStatusTests.cs
> 暴露ocr的版本信息供调用者检查，增加一个检查此项的单测

- BetterGenshinImpact/Core/Config/CommonConfig.cs
看issue看到一些用户的截图，感觉是不是默认启用一下比较好，虽然还会有画面的其他地方出现。。。
> ScreenshotUidCoverEnabled配置的默认值改为true
