BetterGenshinImpact/BetterGenshinImpact.csproj, BetterGenshinImpact/Core/Config/AllConfig.cs, BetterGenshinImpact/GameTask/GameLoading/GameLoading.cs, BetterGenshinImpact/GameTask/GameTaskManager.cs, BetterGenshinImpact/GameTask/SystemControl.cs, BetterGenshinImpact/View/Pages/HomePage.xaml, BetterGenshinImpact/ViewModel/Pages/HomePageViewModel.cs
1. 新增本地安装路径配置，选择原神安装路径后点击启动可以直接拉起原神
2. 新增加载页面触发器，直接启动原神后识别加载完成直接进入游戏
=> 添加本地安装路径配置，直接启动原神

BetterGenshinImpact/GameTask/GameTaskManager.cs
fix #64 
用`Mat.FromStream`绕过`imread`
=> 修复七圣召唤启动报错

BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTrigger.cs
至少预抛竿时关闭自动钓鱼鼠标不会乱动了
还修复了关闭自动钓鱼后错误输出的一些日志
=> 修复#41 预抛竿问题

BetterGenshinImpact/Genshin/Paths/GameExePath.cs
只影响自动检测的路径。本来也没有影响但是看着难受
修复前
修复后
=> 修复游戏安装路径中分隔符不统一

BetterGenshinImpact/GameTask/AutoPick/AutoPickTrigger.cs
=> fix pick bug

BetterGenshinImpact/Core/Recorder/KeyMouseMacroPlayer.cs, BetterGenshinImpact/Core/Recorder/KeyMouseRecorder.cs
1. 将原本基于相对时间的脚本录制与回放修改为基于绝对时间
2. 脚本录制完成后，对鼠标移动事件进行合并，避免回放时丢步
=> 改进键鼠脚本录制与回放精度

BetterGenshinImpact/Core/Recorder/KeyMouseMacroPlayer.cs, BetterGenshinImpact/Core/Recorder/KeyMouseRecorder.cs, BetterGenshinImpact/Core/Recorder/Model/MacroEvent.cs
目前有两个可调参数我还不知道咋调节：
1. KeyMouseRecorder.cs里面的`MergedEventTimeMax`参数，这个参数控制回放时合并的频率
2. KeyMouseRecorder.cs第160行的`if ((now - LastOrientationDetection).TotalMilliseconds > 100.0)`，这个参数控制相机视角记录频率
如果要加开关的话，给第160行的记录功能加开关应该就可以了，回放部分在遇到没有记录相机数据的脚本时，和之前相比表现没有变化
https://github.com/user-attachments/assets/34b6de42-ec97-4531-a5a8-c6ff9c73800f
=> 通过在录制脚本时记录相机视角改善回放精度

BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs, BetterGenshinImpact/Core/Script/Dependence/Model/RealTimeTimer.cs, BetterGenshinImpact/GameTask/AutoDomain/AutoDomainParam.cs, BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/GameTask/AutoGeniusInvokation/AutoGeniusInvokationTask.cs, BetterGenshinImpact/GameTask/AutoGeniusInvokation/GeniusInvokationControl.cs, BetterGenshinImpact/GameTask/AutoGeniusInvokation/GeniusInvokationTaskParam.cs, BetterGenshinImpact/GameTask/AutoGeniusInvokation/Model/Duel.cs, BetterGenshinImpact/GameTask/AutoMusicGame/AutoMusicGameParam.cs, BetterGenshinImpact/GameTask/AutoMusicGame/AutoMusicGameTask.cs, BetterGenshinImpact/GameTask/AutoSkip/AutoTrackTask.cs, BetterGenshinImpact/GameTask/AutoSkip/Model/AutoTrackParam.cs, BetterGenshinImpact/GameTask/AutoTrackPath/AutoTrackPathParam.cs, BetterGenshinImpact/GameTask/AutoTrackPath/AutoTrackPathTask.cs, BetterGenshinImpact/GameTask/AutoWood/AutoWoodTask.cs, BetterGenshinImpact/GameTask/AutoWood/WoodTaskParam.cs, BetterGenshinImpact/GameTask/ISoloTask.cs, BetterGenshinImpact/GameTask/Model/BaseTaskParam.cs, BetterGenshinImpact/GameTask/TaskRunner.cs, BetterGenshinImpact/GameTask/TaskTriggerDispatcher.cs, BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml, BetterGenshinImpact/ViewModel/Pages/HotKeyPageViewModel.cs, BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
=> refactor: solo task

BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
修改了缩放的逻辑，并且缩放后更新鼠标移动的距离，避免因为缩放导致移动距离不够或者过多。本次修改之后，经过鼠标移动，目标传送点基本上在地图整中间（测试了奥奇卡纳塔和枫丹科学院的部分锚点），部分数据参考 https://github.com/babalae/better-genshin-impact/issues/318。
=> 修改了缩放的逻辑，以及因为缩放导致的bug

BetterGenshinImpact/GameTask/AutoFight/AutoFightConfig.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml, BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml
1、判断战斗结束、万叶捡材料、自动拾取，三个配置独立执行。
2、增加 更快检查结束战斗配置，可以根据时间或角色，在一轮角色未走完情况下检查，而加快检查战斗速度。 
3、增加了万叶拾取的配置
4、增加 检查战斗结束检查的延时 ，可根据不同人物更精细的策略。
=> 增加针对战斗的细化配置

BetterGenshinImpact/GameTask/AutoTrackPath/Assets/tp.json
=> 修复虹灵的净土秘境消失的问题

Fischless.GameCapture/Graphics/GraphicsCapture.cs
windows10_1909版本的WGC不支持IsCursorCaptureEnabled，加了个动态判断防止异常与抓屏失败等。
但是这样就有可能会抓到光标导致图像识别失败，但是个人认为瘦死的骆驼比马大，没有这个api就不调用即可，好歹还能用一下 如果有必要，后面可以考虑加一个弹窗警告一下啥的，但是这样可能会让用户糟心，总不能逼人家换个系统吧？但是不弹窗呢又好像向用户隐藏了某些可能存在的错误，好像又不太对啥的。
只能说云原神的限制还是大了一点，要不要加弹窗我无法决策，还是由其他人来吧。
=> 修正windows10_1909版本WGC故障

BetterGenshinImpact/Core/Config/PathingPartyConfig.cs, BetterGenshinImpact/Core/Script/Dependence/AutoPathingScript.cs, BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs, BetterGenshinImpact/Core/Script/EngineExtend.cs, BetterGenshinImpact/Core/Script/Group/ScriptGroupProject.cs, BetterGenshinImpact/Core/Script/Project/ScriptProject.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/GameTask/AutoPathing/Handler/AutoFightHandler.cs, BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs, BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml
路径追踪增加  允许在jsScript脚本中启用此路径追踪配置、覆盖JS中的自动战斗配置 。默认为否，开启后可以使JS脚本中的路径追踪和自动战斗，使用该调度器所配置的参数运行
=> 路径追踪增加增加  允许在jsScript脚本中启用此路径追踪配置、覆盖JS中的自动战斗配置 。

BetterGenshinImpact/GameTask/AutoFight/AutoFightConfig.cs, BetterGenshinImpact/GameTask/Common/Job/ScanPickTask.cs, BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml
优化了锄地战斗后捡掉落物的逻辑，具体为
1. 把原本将指针移到识别框内的逻辑改成向人物中线的左或者右反复微调。
2. 暴露一些参数供用户调整（在 独立任务-自动战斗-自动拾取凋落物 处）
=> 优化锄地战斗后捡掉落物的逻辑

BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs
我发现战斗结束的白块检测点在我机器上并没有对准，导致战斗结束判断正确率不到5成，于是调了下坐标
在2K和1080P下都测试了，下面是在白点不动之后的截图
1080P：
2K：
如果有人白块坐标不一样请附图告知我
=> bugfix: 战斗结束检测

BetterGenshinImpact/GameTask/AutoPathing/Model/Enum/ActionEnum.cs, BetterGenshinImpact/GameTask/AutoPathing/Model/Enum/WaypointType.cs, BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
添加一个朝向类型的节点，只转向目标点，不移动。
大佬看一下，这样添加是不是就可以了。
必要性：
脚本中实现固定朝向一个点很不稳定：用path精度不够，且可能会绕点弧线或有偏离，导致最终朝向不是两点连线的方向；用target可能走过去又回头。
另外，这段代码大佬看一下，
```
if (
...
!string.IsNullOrEmpty(waypoint.Action)
&& waypoint.Action != ActionEnum.StopFlying.Code
&& waypoint.Action != ActionEnum.NahidaCollect.Code
&& waypoint.Action != ActionEnum.CombatScript.Code
&& waypoint.Action != ActionEnum.Mining.Code
...
)
{
await MoveCloseTo(waypoint);
}
```
这是让非target类型，且不是上述动作，的节点强制去小碎步接近。
force_tp, up_down_grab_leaf, log_output这几个其实也不用；
就这几个 pick_around, hydro_collect, electro_collect, anemo_collect，
如果这几个没有大量现存不用target的脚本，上述特殊判断可以删掉，以后让脚本中按需指定成target类型；如果有历史包袱，用waypoint.Action == ...这几个特例可能会好看一点。
=> auto pathing: add `Orientation` to `WaypointType`

BetterGenshinImpact/View/Controls/Webview/WebpagePanel.cs
#1065
WebView2 进程不会继承 parent process 的管理员权限，所以当 BGI 安装在 Program Files 文件夹内时无法创建数据目录；
解决方法时在 WebView2 进程启动前创建一个 EveryOne 拥有完全控制权限的文件夹。
=> Fix the issue of WebView2 UserDataFolder cannot be created

BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/GameTask/Common/Job/ScanPickTask.cs
攀爬时没法切队切人，所以提前取消攀爬。
采集前取消攀爬也有点用，在墙上一直按W会一直上墙。
~~**注：改动未经本人测试，只通过了编译**
但应该不至于影响别的功能（我测了会删掉这两行，也欢迎帮我测试）~~
经测试显著减少挂墙上的情况
PS：linter一看tryTimes是灰的没绷住，顺手改了
=> 在换队/换人/采集之前取消攀爬

BetterGenshinImpact/GameTask/AutoFight/AutoFightConfig.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml, BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml
本人低配置下自动锄地检查战斗结束有概率误判（确实结束但认为没结束，在低配置下发生概率会高一点）。在QQ频道那边看到过类似的问题，于是打算提升这个换队延迟时间，expose出来给用户调整，默认依然为0.45
=> feature：自动战斗增加换队延迟

BetterGenshinImpact/Core/Config/KeyBindingsConfig.cs, BetterGenshinImpact/Core/Script/Dependence/GlobalMethod.cs, BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/View/Pages/CommonSettingsPage.xaml, BetterGenshinImpact/View/Pages/KeyBindingsSettingsPage.xaml
~~_嗨嗨嗨，我又来污染仓库了_~~
最近在执行JS脚本`AutoArtifacts_A_B_Extra`时发现，角色走到某些地方的行为有点奇怪，要么日墙卡死要么莫名其妙摔死，但是并未在脚本仓库看到相关Issue的提出，遂自查发现是由于路径跟踪中的简易脚本无法正常执行（如`【额外】狗粮-纳塔-鸡屁股+7个-f.json`中附身龙并遁地的操作就因为我将特殊玩法的按键改为Q而无法正常执行），导致路径追踪出现意外情况，于是灵机一动去改了`Avatar.cs`和`GlobalMethod.cs`中模拟键盘输入的代码，使其在执行脚本或战斗宏遇到KeyDown、KeyUp、KeyPress时能够从默认键位映射到实际的键位；对鼠标按键则不进行映射，毕竟原神本来也不支持修改。
* 全局按键映射功能默认关闭，需要在设置页手动启用
* 部分玩法中的按键绑定独立于按键绑定设置，且无法更改，暂不清楚中央仓库中是否有脚本会在执行期间进入特殊玩法，或许需要在功能开关的UI加上“（实验性）”描述文本提示用户谨慎开启
* 或许需要提供一个在脚本执行期间临时关闭全局按键映射的方法
=> feat: 全局按键映射支持

BetterGenshinImpact/Core/Recorder/KeyMouseRecorder.cs
- 合并鼠标事件后，输出JSON前判断`currentMerge`是否为`null`，若否，则将`currentMerge`添加到`mergedMacroEvents`的末尾，防止丢失最后一个`MacroEvent`
实测最后一个`MacroEvent`有很大概率会直接丢失，即使是`MouseMoveBy`或`MouseMoveTo`事件，只不过坐标一般很小，难以察觉。
=> fix #1178 修复保存键鼠脚本时丢失最后一个MacroEvent的问题

BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTask.cs, BetterGenshinImpact/GameTask/AutoFishing/Behaviours.cs, BetterGenshinImpact/GameTask/AutoFishing/Blackboard.cs, BetterGenshinImpact/GameTask/AutoFishing/Model/Fishpond.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ChooseBait.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.GetFishBoxArea.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.GetFishpond.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ThrowRod.cs
一个是今天上午群友发现的在钓雷鸣仙时，因“文字块”识别通过而误识别了鱼咬钩，于是进入寻找拉扯框的死循环的Bug；
还有就是现阶段抛竿还有有些问题，要进行一些优化。
但咬钩识别、和抛竿这两块儿的主体是沿用的旧代码，hutao的那块是个黑箱可以不管，但外围仍有一些逻辑，需要先理清现有思路，再看看怎么优化，最好还能配上测试用例
=> 咬钩后拉扯框识别的优化，以及着手优化抛竿

BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
调整缩放等级之后把鼠标移动到屏幕中心，避免鼠标挡住图标影响 GetBigMapZoomLevel 获取当前的缩放等级而导致传送失败。
=> fix: move mouse to center after adjust zoom level

BetterGenshinImpact/View/Pages/TriggerSettingsPage.xaml, BetterGenshinImpact/ViewModel/Pages/TriggerSettingsPageViewModel.cs
按照文档里的原意并没有做成可以直接修改的下拉框
而是配置中有不一样的按键的时候加到下拉框的可选项里面
这样如果想自定义的话仍旧需要修改配置文件
个人认为比做到UI里面直接配置要好
=> 修复 #1262 自动拾取按文档指引改键无效

BetterGenshinImpact/GameTask/AutoPathing/Handler/ActionFactory.cs, BetterGenshinImpact/GameTask/AutoPathing/Handler/StopFlyingHandler.cs, BetterGenshinImpact/GameTask/AutoPathing/Model/WaypointForTrack.cs, BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
1. feat: add action_params(StopFlyingWaitTime) to stop_flying;
2. fix: ensure next step only proceeds after stop_flying.
**测试用例：**
```
{
"info": {
"name": "下落攻击等待时间测试",
"type": "collect",
"author": "秋云",
"version": "1.0",
"description": "下落攻击等待时间测试，附赠火史莱姆。",
"bgiVersion": "0.43.1"
},
"positions": [
{
"id": 1,
"x": 1391.01,
"y": 515.44,
"action": "",
"move_mode": "walk",
"type": "teleport"
},
{
"id": 2,
"x": 1371.81,
"y": 530.83,
"action": "",
"move_mode": "walk",
"type": "path"
},
{
"id": 3,
"x": 1394.83,
"y": 546.72,
"action": "",
"move_mode": "walk",
"type": "path"
},
{
"id": 4,
"x": 1379.88,
"y": 593.19,
"action": "stop_flying",
"move_mode": "fly",
"type": "path",
"action_params": "1000"
},
{
"id": 5,
"x": 1379.88,
"y": 593.19,
"action": "fight",
"move_mode": "walk",
"type": "path"
}
] …
```
=> feat: add action_params(StopFlyingWaitTime) to stop_flying

BetterGenshinImpact/Service/Notification/NotificationConfig.cs, BetterGenshinImpact/Service/Notification/NotificationService.cs, BetterGenshinImpact/Service/Notifier/FeishuNotifier.cs, BetterGenshinImpact/View/Pages/NotificationSettingsPage.xaml
为查看BGI任务状态提供便利, 编写了飞书图片推送的代码。
请您随意编辑代码, 以及合并或关闭PR。望对仓库有所帮助。
=> :sparkles: 飞书通知时带有图片(需要配置app,并且在飞书后台增加上传图片权限)

BetterGenshinImpact/Service/ScriptService.cs
发现通过调度器直接原神启动时，进入主界面前有概率闪退，可能是while (true)里的截图太频繁导致，添加sleep后测试该问题已解决
=> 通过调度器启动时，添加sleep防止闪退

BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs, BetterGenshinImpact/GameTask/Common/Job/ArtifactSalvageTask.cs, BetterGenshinImpact/GameTask/Common/Job/ArtifactSalvageTask.en.resx, BetterGenshinImpact/GameTask/Common/Job/ArtifactSalvageTask.fr.resx, BetterGenshinImpact/GameTask/Common/Job/ArtifactSalvageTask.zh-Hans.resx, BetterGenshinImpact/GameTask/Common/Job/ArtifactSalvageTask.zh-Hant.resx, Test/BetterGenshinImpact.UnitTest/CoreTests/RecognitionTests/OCRTests/PaddleOcrServiceTests.cs
分解圣遗物目前是只有自动秘境任务中会调用，我本地界面做了个独立任务按钮测了一下没问题，下一步也打算继续升级成一个单独的独立任务，因为自带的圣遗物锁定实在不好用，想做个自己的分解五星逻辑
=> 分解圣遗物支持多语言，顺便修了一下5.5版本快速选择筛选星级逻辑

BetterGenshinImpact/BetterGenshinImpact.csproj, BetterGenshinImpact/Core/Recognition/OpenCv/CommonExtension.cs, BetterGenshinImpact/Core/Recognition/OpenCv/FeatureMatch/FeatureMatcher.cs, BetterGenshinImpact/Core/Recognition/OpenCv/OpenCvCommonHelper.cs, BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs, BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs, BetterGenshinImpact/GameTask/AutoFishing/AutoFishingImageRecognition.cs, BetterGenshinImpact/GameTask/AutoFishing/Behaviours.cs, BetterGenshinImpact/GameTask/AutoFishing/Blackboard.cs, BetterGenshinImpact/GameTask/AutoFishing/Model/Fishpond.cs, BetterGenshinImpact/GameTask/AutoSkip/AutoTrackTask.cs, BetterGenshinImpact/GameTask/AutoSkip/ExpeditionTask.cs, BetterGenshinImpact/GameTask/AutoSkip/Model/HangoutOption.cs, BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs, BetterGenshinImpact/GameTask/Common/Map/BigMap.cs, BetterGenshinImpact/GameTask/Common/Map/Camera/CameraOrientationFromLimint.cs, BetterGenshinImpact/GameTask/Common/Map/CharacterOrientation.cs, BetterGenshinImpact/GameTask/Model/Area/ImageRegion.cs, BetterGenshinImpact/GameTask/Placeholder/PlaceholderTrigger.cs, Fischless.GameCapture/BitBlt/BitBltCapture.cs, Fischless.GameCapture/Fischless.GameCapture.csproj, Fischless.GameCapture/Graphics/GraphicsCapture.cs, Fischless.GameCapture/Graphics/Helpers/Texture2DExtensions.cs, Test/BetterGenshinImpact.Test/Dataset/AvatarClassifyGen.cs, Test/BetterGenshinImpact.Test/Dataset/AvatarClassifyTransparentGen.cs, Test/BetterGenshinImpact.Test/Simple/AllMap/KeyPointMatchTest.cs, Test/BetterGenshinImpact.Test/Simple/MiniMap/CharacterOrientationTest.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ChooseBait.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/AutoFishingTests/BehavioursTests.ThrowRod.cs
升级了几个依赖包
- PaddleOCR 2.7.0.3 : 在PaddleOCR 2.7.0.2中修复了之前版本涉及到的线程安全问题。
- OpenCvSharp4 : 这个属于是必须升级的(有依赖)
- 尝试修复了一下bitblt的爆炸，这个还有待测试
其他: [OpenCvCommonHelper.cs](https://github.com/babalae/better-genshin-impact/pull/1381/files#diff-9accab0d38f64922a923e38be58cec2245dd1efa1e58e20c2aad6aa5315639ba)
把没必要用unsafe的方法换掉了
其他截图也可能存在问题，但是先修了这个比较着急的。
=> 尝试修复闪退&一些OpenCv增强

BetterGenshinImpact/BetterGenshinImpact.csproj, Fischless.GameCapture/Fischless.GameCapture.csproj
灵！
来自 https://github.com/sdcb/PaddleSharp/issues/115
=> 👻更旧OpenCvSharp4相关包版本到4.10.0.20240616(据说这样OCR不容易爆炸)

Fischless.GameCapture/BitBlt/BitBltCapture.cs, Fischless.GameCapture/BitBlt/BitBltSession.cs
rt。[重构 BitBltCapture 并添加 BitBltSession 以提高线程安全性](https://github.com/babalae/better-genshin-impact/commit/bc0aa8705de4eca893ede8414d329e9cd7d9e83a)
带来的变化:
现在截图尺寸可能不会实时响应窗口变化(最小化/尺寸变化)
但是目前游戏的应用场景不会存在频繁更改分辨率的问题。一般游戏也不会频繁变换窗口。实测可以有效降低cpu占用。(虽然没降多少（x
ps:DX截图爆炸修起来很头疼。不如优化一下bitblt，跑的也挺快的鸭。
=> bitblt截图修改:复用缓冲区以减少每次截图时的内存分配

BetterGenshinImpact/Core/Script/Dependence/Genshin.cs, BetterGenshinImpact/Core/Script/EngineExtend.cs, BetterGenshinImpact/GameTask/AutoPathing/Navigation.cs, BetterGenshinImpact/GameTask/AutoPathing/PathRecorder.cs
顺便意外发现了路径记录器在传送之后获取 (0,0) 的原因，修改之后已经修复了。
测试用例：
从小地图获取坐标
```js
(async function () {
await genshin.returnMainUi();
let position = genshin.getPositionFromMap();
log.info(`当前位置: X=${position.X}, Y=${position.Y}`);
})();
```
从大地图获取坐标
```js
(async function () {
await genshin.returnMainUi();
keyPress('M');
await sleep(1000);
let position = genshin.getPositionFromBigMap();
log.info(`当前大地图位置: X=${position.X}, Y=${position.Y}`);
keyPress('VK_ESCAPE');
})();
```
=> feat(js): 获取大地图和小地图中心点坐标

Fischless.GameCapture/BitBlt/BitBltCapture.cs, Fischless.GameCapture/BitBlt/BitBltSession.cs
[Bitblt:GDI直接返回转换后的位图，不再由CV二次转换](https://github.com/babalae/better-genshin-impact/commit/474d6bf99bd7838b8e9af43a3ce7986cdbdb7340)
测试环境为 8bit色深，不开启hdr
=> bitblt 还能更快

BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/GameTask/AutoPathing/Handler/ElementalCollectHandler.cs
啊啊啊啊啊非常抱歉！
我记得我明明有特别改了一下这边！我甚至还编译了一份测试过，可能是我没有push上去qaqqqq
另外: 现在 PathExecutor 中的 TryPartyHealing  https://github.com/babalae/better-genshin-impact/blob/0b6d0d231e2eeda90dd1df32b88da961aa400ea5/BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs#L505 不知道还有没有必要。如果可以的话是不是改成战斗脚本更合适一些？现在就只有这边没办法正常计算cd了
=> 修复UseSkill调用之后没有正确调用cd计算函数的问题，增加注释

Fischless.GameCapture/BitBlt/BitBltCapture.cs
失败之后强制重置截图会话。而不是原来的等待1秒后重试。
一秒钟之后重试会使得挂机时候反复截图失败导致终止任务。
但是我没有测试环境，我挂机始终无法复现。
所以尝试着按着群里的反馈修了一下，但是没办法进一步测试。
=> 优化BitBlt截图逻辑，增加失败重试机制以提高截图成功率

BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
把 UpdateActionSchedulerByCd 放到了 [CombatScenes.cs](https://github.com/babalae/better-genshin-impact/compare/main...Takaranoao:main-fix-cd?expand=1#diff-5db4c0c17e1f11cdc37ef5fb0af089ced3fb9249d5066d863308ce66c4c5ee7a) 里面
然后修复了跳过判定的逻辑，不过目前跳过的话还是只支持中文标准角色名，不支持英文和别名。
之前跳过判定逻辑有bug，会导致对不可跳过的角色进入跳过逻辑
=> 修复手动设置cd不生效和快速跳过战斗时有时会导致刷屏的问题。

BetterGenshinImpact/Model/SettingItem.cs
修复问题：
1. 默认值赋值有问题，因为Default的类型是object,反序列化后Default是JsonElement的实例，而不是基本数据类型。因此，原先的`select`和`checkbox`的赋值会强转异常（如果setting.json中配置了default的话）。
```cs
public object? Default { get; set; }
```
```cs
comboBox.SelectedItem = Default;
checkBox.IsChecked = (bool)Default;
```
2.当首次编辑js配置时，jsScriptSettingsObject是一个空对象，没有任何的属性，这时候双向绑定到组件上会导致无法正确显示setting.json的默认值（BindingOperations.SetBinding时会清空前面的赋值）。因此，当用户没有修改过配置时，先将默认值设置到上下文，再绑定到组件。
=> fix(js): 修复创建配置组添加js脚本后，首次编辑js脚本自定义配置时，组件无法正确绑定到setting.json中的默认值

BetterGenshinImpact/GameTask/AutoPathing/Handler/ActionFactory.cs, BetterGenshinImpact/GameTask/AutoPathing/Handler/SetTimeHandler.cs, BetterGenshinImpact/GameTask/AutoPathing/Model/Enum/ActionEnum.cs, BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs, BetterGenshinImpact/GameTask/Common/Job/ReturnMainUiTask.cs, BetterGenshinImpact/GameTask/Common/Job/SetTimeTask.cs
钓鱼还是使用的老版本，需要显式设置 skipTimeAdjustmentAnimation 为 true。
测试用例（使用时瞬）：
```json
{
"info": {
"name": "setTimeTest",
"type": "collect",
"author": "秋云",
"description": "测试设置时间"
},
"positions": [
{
"x": 7845.3203125,
"y": -2048.837890625,
"type": "teleport",
"move_mode": "walk"
},
{
"x": 7843.3994140625,
"y": -2057.9306640625,
"type": "path",
"move_mode": "walk",
"action": "set_time",
"action_params": "18:00"
}
]
}
```
测试用例（不使用时瞬）：
```json
{
"info": {
"name": "setTimeTest",
"type": "collect",
"author": "秋云",
"description": "测试设置时间"
},
"positions": [
{
"x": 7845.3203125,
"y": -2048.837890625,
"type": "teleport",
"move_mode": "walk"
},
{
"x": 7843.3994140625,
"y": -2057.9306640625,
"type": "path",
"move_mode": "walk",
"action": "set_time",
"action_params": "18:00:false"
}
]
}
```
=> feat(action): set_time

BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
BUG表现：地图追踪反复左右移动地图，有时候点到窗口外面
复现方法：显示器>100%缩放，游戏内地图缩放最大，执行地图追踪
可能相关：#1216
=> 修复高DPI下TP地图移动

BetterGenshinImpact/Core/Script/Dependence/Genshin.cs, BetterGenshinImpact/GameTask/Common/Job/SwitchPartyTask.cs
1.释放切换队伍失败状态到JS,否则未能打开选择队伍页面后，js会直接退出任务。
2.未找到换队页面，恢复抛出异常，否则地图追踪无法捕获异常到七天神像。
=> 释放切换队伍失败状态到JS，未找到换队页面抛出异常。

BetterGenshinImpact/View/Windows/PromptDialog.xaml
问题：当Prompt的TxtQuestion文本过长时，无法PromptDialog无法自适应宽度来展示溢出的文本
修复：在保证`MinWidth`不变的情况下，配置SizeToContent="Width"
修复前：
修复后：
=> fix(ui): 修复Prompt的TxtQuestion过长时，对话框无法完整显示

BetterGenshinImpact/GameTask/CaptureContent.cs
修复 #1561
顺手加的，没测地图追踪。
CaptureToRectArea函数返回后CaptureContent会被GC，导致后面访问CaptureRectArea都失败了。
=> 手动管理 CaptureContent Dispose

Fischless.GameCapture/Graphics/GraphicsCapture.cs
之前 OpenCV CPU 处理 HDR 图像时，`OnFrameArrived` 会抢占 CPU 导致 UI 卡死，当时改成多线程了。
Windows 10 会崩溃，回退。
Fix #1570
=> 修复Win10下WGC截图COM错误

BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs
=> 修复自动秘境的文案错误

BetterGenshinImpact/GameTask/AutoFishing/Behaviours.cs
本机自动钓鱼经常把游标按出区间外，研究了一下貌似是矩形检测时会出现非常规结果。
简单重构了一下，改动：
1. 采用了我觉得更有道理的变量名
2. 判断出现异常后无视
3. 初始MouseEvent应当是松开
4. ~~用左右两边矩形宽度比较取代原本神秘逻辑，引入了一个靠左的比例使游标更不易弹出区间~~ 已revert
=> 优化自动钓鱼拉条时游标弹出目标区间的情形

BetterGenshinImpact/ViewModel/Pages/MapPathingViewModel.cs
`bettergi-scripts-list`重新整理文件夹结构后方便查找了许多，不过由于追踪任务移动到了子文件夹内，地图追踪界面不显示它们的图标了。
此PR添加对子文件夹图标的支持：
=> fix: 修复`AutoPathing`下的非顶层文件夹不显示图标的问题

BetterGenshinImpact/Core/Config/OneDragonFlowConfig.cs, BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
因为发现每天凌晨执行一条龙的时候会刷到错误的副本，所以做此修改。
=> 将每天的定义更改4点后。

BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs, BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs
#1645 的部分修改，只是将路径追踪相关的日志改为debug级别，不含日志筛选功能。
（和日志筛选不冲突，即使未来添加日志筛选，路径追踪相关的日志似乎也无需使用info级别，使用debug级别记录到文件中即可）
按功能需求合入，如无需此修改可直接关闭PR
=> 将路径追踪相关的日志改为debug级别 (#1645)

BetterGenshinImpact/GameTask/AutoFight/Model/AvatarMacro.cs, BetterGenshinImpact/GameTask/AutoFight/OneKeyFightTask.cs, BetterGenshinImpact/User/avatar_macro.json, BetterGenshinImpact/View/Pages/MacroSettingsPage.xaml
- 新增角色级别的宏优先级配置(MacroPriority)
- 支持每个角色独立设置使用的宏编号(1-5)
- 优化宏优先级验证和回退逻辑
- 更新UI说明文本和所有角色配置
https://github.com/babalae/better-genshin-impact/issues/1668 当前问题还存在
=> feat: 支持角色个性化战斗宏优先级设置

BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml
Reverts babalae/better-genshin-impact#1681
点击按钮自动切换交互没问题，但是展开非展开的交互强绑定不符合普通用户操作习惯
=> Revert "优化交互界面。"

BetterGenshinImpact/GameTask/Common/Job/GoToSereniteaPotTask.cs, BetterGenshinImpact/View/MainWindow.xaml, BetterGenshinImpact/View/Pages/OneDragonFlowPage.xaml, BetterGenshinImpact/ViewModel/Pages/TaskSettingsPageViewModel.cs
#1752 #1750 
1、尘歌壶点击房屋图标后，会进行延时判断重试。
2、尘歌壶购买周期始于每天4点。
2、主页左侧菜单，在调度器展开后，设置按键会有几个像素的超出边框，修复。
3、一条龙每周秘境执行周期说明UI显示调整，UI微调。
4、一条龙快捷键修复。
=> 一条龙尘歌壶进入添加重试/UI微调/一条龙快捷键修复 #1750 #1752

BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs, BetterGenshinImpact/GameTask/Common/Job/ExitAndReloginJob.cs, BetterGenshinImpact/GameTask/Common/NewRetry.cs
1. 300ms检测一次是否点击出了传送，最多检测1800ms；
2. 添加带截图的WaitForElementDisappear重载，避免重复截图；
3. 增加了退出重登的超时时间，避免部分低性能设备超出原设定的最长时间导致任务失败。
=> fix: 优化传送点点击的逻辑，增加退出重登的延时

BetterGenshinImpact/GameTask/AutoPathing/Handler/MiningHandler.cs
提高诺艾尔在大剑挖矿角色选择列表中的优先级。
当前BetterGI建议的1号位角色位迪希雅，而迪希雅在此列表中排名靠前，导致玩家在运行大剑挖矿脚本中大概率选择迪希雅作为挖矿角色。迪希雅的问题是她的连续攻击第3段和第4段会向前冲刺一段距离，可能会使其超过矿石的位置，导致矿石只被攻击2下，进而挖不到矿。
诺艾尔的挖矿优势在于，她的四次攻击每次都会重新调整攻击方向，即使前两次攻击导致角色位移了一段距离，下一次攻击也会重新调整方向正对矿石，从而提高了挖矿的成功率。
并且诺艾尔作为新手祈愿必出角色，大部分玩家都应该持有。
基于以上原因，建议将诺艾尔作为优先选择。
=> 优先使用诺艾尔作为大剑挖矿角色

BetterGenshinImpact/GameTask/Common/Job/SwitchPartyTask.cs
=> 延长换队失败的判断时间

BetterGenshinImpact/Core/Recognition/RecognitionObject.cs
模版匹配添加颜色遮罩,有一些情况识别的模版差别很小，例如识别原粹树脂，脆弱树脂和须臾树脂，用一个模版全部都成功匹配成功，如果改用颜色遮罩，抠图把底色设置为纯绿色(0, 255, 0)，就可以正常区别进行匹配，我测了一下，效果可以，就看有没必要释放出来给JS。
=> JS图像识别模版匹配添加颜色遮罩

BetterGenshinImpact/App.xaml, BetterGenshinImpact/View/Behavior/ClipboardInterceptor.cs
支持 (Rich)TextBox 复制/剪切/粘贴 和 DataGrid 复制，TextBox默认生效，可通过附加属性 ClipboardInterceptor.EnableSafeClipboard 启用
https://github.com/user-attachments/assets/2bfa27b5-4f83-4968-8597-7b6cd9e5ad62
https://github.com/user-attachments/assets/f907e32e-5a4d-4ff9-9a0b-47eac218a3a8
https://github.com/user-attachments/assets/74326890-7854-4419-bef3-a4b0d6a83d51
是 wpf 的通用问题，剪贴板被其他软件占用时会出现 OpenClipboard 失败，会报一堆的 com 错误，并且 SetDataObject 存在重试机制，会重试 10 次，间隔 100 ms，体现出来就是 1s 的阻塞。
常见于开着各种 远程桌面 / Notepad++ 剪贴历史记录 等软件/功能 的时候。
因为剪贴板被占用必报一次 `所请求的剪贴板操作失败`，第一次复制/剪切的时候可能会比较卡顿，但后续操作会回复正常。
Ported from the MaaWpfGui project https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/a79980daf2a470781686acb62eb6f932f76563b9
=> fix: 规避 WPF 剪贴板卡顿，修复剪切不清除文本的问题

BetterGenshinImpact/Core/Config/ScriptConfig.cs, BetterGenshinImpact/Core/Script/ScriptRepoUpdater.cs, BetterGenshinImpact/View/Windows/ScriptRepoWindow.xaml, BetterGenshinImpact/View/Windows/ScriptRepoWindow.xaml.cs
出于测试和奇奇怪怪的加速需求，有时候可能会从非官方源更新脚本仓库
以及选择项个人感觉应该写入配置文件
顺便修了更新出错时候进度条不重置的问题
=> 选中的更新渠道URL写入配置文件并允许从自定义URL更新脚本仓库

BetterGenshinImpact/GameTask/AutoDomain/AutoDomainTask.cs, BetterGenshinImpact/GameTask/AutoDomain/Model/ResinStatus.cs, BetterGenshinImpact/GameTask/Common/Job/SwitchPartyTask.cs, BetterGenshinImpact/ViewModel/Pages/OneDragonFlowViewModel.cs
自动秘境换队改到秘境页面/原粹识别优化
复用现在的切换队伍函数，加了标志位坐区分，省略几个步骤就可以了，测了几天还可以，目前没有发生影响其他情况的使用。
周末序号添加了一个空字符，用于不改变选择。
传送到秘境后，走到秘境过程进行了优化。
另外原粹树脂群里有反馈说存在不稳定，很多时候数字1的识别都不是很稳定，把后面的/200也截图下来，改用Match，这个方法好像挺稳定的，当识别都有其他数字，识别1的成功率就会更高。
=> 自动秘境换队改到秘境页面/原粹识别优化

BetterGenshinImpact/Service/Notification/NotificationConfig.cs, BetterGenshinImpact/Service/Notification/NotificationService.cs, BetterGenshinImpact/Service/Notifier/TelegramNotifier.cs, BetterGenshinImpact/View/Pages/NotificationSettingsPage.xaml
添加了代理支持功能，解决了 Telegram 通知无法通过代理的问题。详见 #1775
为了防止其他地方使用到代理，就在telegramNotifier中单独开启了httpClient单独判断是否需要代理环境
经测试，能够在代理环境情况下接收到消息
=> 给telegramNotifier添加代理功能支持

BetterGenshinImpact/Service/Notification/NotificationConfig.cs, BetterGenshinImpact/Service/Notification/NotificationService.cs, BetterGenshinImpact/Service/Notifier/DiscordWebhookNotifier.cs, BetterGenshinImpact/View/Pages/NotificationSettingsPage.xaml, BetterGenshinImpact/ViewModel/Pages/NotificationSettingsPageViewModel.cs
related: #1632
ref: https://discord.com/developers/docs/resources/webhook#execute-webhook
右邊的 thumbnail 點進去會有全圖
可能要看看用不用把預設的頭像地址刪掉，我是在官網那邊拿的 URL
=> feat: Discord Webhook notification

BetterGenshinImpact/GameTask/AutoFight/AutoFightConfig.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightSeek.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/View/Pages/TaskSettingsPage.xaml, BetterGenshinImpact/View/Pages/View/ScriptGroupConfigView.xaml
1、此为实验功能，供参考，使用库自带的OpenCvCommonHelper.Threshold进行色块检测，怪物头上的血条固定颜色Scalar bloodLower = new Scalar(255, 90, 90);，
2、目前判断还是比较准确的，大世界好像只有怪物头上血条是这个颜色，检测到颜色后用Cv2.ConnectedComponentsWithStats计算色块的连通性，包含色块数量和长宽，用于判断怪物的远近，做对应的移动动作
3、目前测试两天，有用，但好像也用处不大？怪物太远了，血条都没显示，也没有打的必要，其实可以用来检测是否有怪物，跳过开队伍检测，加快战斗速度，这个比较有用，反正大家可以讨论讨论，效果如何吧。
4、加了开关，默认关闭。
=> 检测战斗结束增加旋转寻找敌人实验性功能

BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
重构搜索后修复了搜索功能形同虚设，只能搜索最表面父文件夹的问题。
**重构之前无法搜索除父文件夹外的任何内容：**
样张：
**重构之后默认搜索能根据基本需求，搜索到大部分内容（“地方特产”目录可索引到第三级目录，其他目录可索引到第二级目录）**
样张：
**新增的深度搜索功能支持搜索全部的文件**
样张：
=> 重构添加地图追踪任务页面的搜索功能，同时添加深度搜索功能

BetterGenshinImpact/Core/Script/ScriptRepoUpdater.cs, BetterGenshinImpact/Core/Script/WebView/RepoWebBridge.cs, BetterGenshinImpact/GameTask/Common/Job/ExitAndReloginJob.cs, BetterGenshinImpact/View/Windows/PromptDialog.xaml.cs, BetterGenshinImpact/ViewModel/Pages/ScriptControlViewModel.cs
1、添加了一些文本框自动聚焦
2、修复调度器复制组点击取消后会有异常返回
3、点击更新仓库后会将新的repo.json与旧版比较，有更新的部分将会添加一个新的hasUpdate=true的属性，随后将带有更新提示的repo_update.json添加到Repos路径下（放置在原处会引起git校验失败）
4、桥接方法新增UpdateSubscribed与ClearUpdate，能够提供单个有更新节点的“去红点”与覆盖式的全部清除，后者采用将repo.json覆盖repo_update.json的方式
=> 小优化及新增脚本仓库桥接支持

BetterGenshinImpact/Core/Script/Project/Manifest.cs, BetterGenshinImpact/Core/Script/ScriptRepoUpdater.cs
在JS脚本的manifest.json中添加saved_files字段（数组），可保存指定的文件（支持通配符与正则表达式）
示例：
=> 增加JS保存文件支持

BetterGenshinImpact/Core/Config/HardwareAccelerationConfig.cs, BetterGenshinImpact/Core/Recognition/ONNX/BgiOnnxFactory.cs, BetterGenshinImpact/View/Pages/View/HardwareAccelerationView.xaml
有些PC在奇奇怪怪环境下嗅探PATH会导致异常
异常处理了
默认这个功能关闭，小白一般也用不上
=> CUDA路径嗅探默认关闭

BetterGenshinImpact/GameTask/Common/Job/ClaimBattlePassRewardsTask.cs, BetterGenshinImpact/GameTask/Common/Job/ClaimBattlePassRewardsTask.en.resx, BetterGenshinImpact/GameTask/Common/Job/ClaimBattlePassRewardsTask.fr.resx, BetterGenshinImpact/GameTask/Common/Job/ClaimBattlePassRewardsTask.zh-Hans.resx, BetterGenshinImpact/GameTask/Common/Job/ClaimBattlePassRewardsTask.zh-Hant.resx
当前最新的代码领取纪行奖励仍然会失败，经过调试发现是OCR识别不准确导致的。部分log如下，使用"键"作为关键字匹配效果不甚理想，因为这个字复杂容易出错，所以在本PR中增加一个关键字，只要有一个匹配成功即认为成功
```
[19:10:31.419] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
"—钧"
[19:10:31.419] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
"解锁珍珠纪行"
[19:10:31.419] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
"键领取"
[19:10:31.419] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
"UID: xxxxxxxxx"
[19:10:31.421] [INF] BetterGenshinImpact.GameTask.Common.TaskControl
纪行："无需领取"
```
=> 提高领取纪行奖励的鲁棒性

BetterGenshinImpact/Service/Notifier/DiscordWebhookNotifier.cs
**Fixes "badrequest" error for blank usernames**
- The previous code would send an empty username field in the JSON payload if the value was blank, causing Discord's API to return a "bad request" error. This change modifies the serialization logic to completely omit the username field from the payload if it is null or blank.
**Fixes malformed URLs with existing query parameters**
- The original URL string was being built with simple string concatenation. This would break if the provided webhook URL already contained a ? for existing query parameters (e.g., for thread_id). The code now uses a UriBuilder to safely and correctly add the with_components=true query parameter without corrupting the URL.
=> fix: discord webhook notification

BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs
菈乌玛的修正问题有三个：
一、TrySwitch默认重试4次，传入Offset60Fix的最大为3，所以涉及的切人（行走位和战斗）都不会触发修正，解决方法：Offset60Fix中把改为if (i > 2)。
二、相关rect如重新启动任务会重置，导致切人那边不知道现在的真实状态，例如用菈乌玛跑了一个地图追踪，目前-14后的rect，跑完我停止任务，重新执行一个任务，rect会重置为非-14，那么状态就会出错，默认的rect是初始值，触发切人修正的基准应该为-14，导致修正出错。解决办法：每次触发纠正以初始为基准进行-14或+14。
三、正常任务中，因为卡地形，出招卡切换等，可能会导致切换失败超过3次，在非需要修正下触发多次+14的操作，所以，切人修正得正反修正以纠正可能的修正错误。
=> 菈乌玛入队相关情况修复

BetterGenshinImpact/GameTask/AutoFight/AutoFightTask.cs, BetterGenshinImpact/GameTask/AutoFight/Model/Avatar.cs, BetterGenshinImpact/GameTask/AutoFight/Model/CombatScenes.cs, BetterGenshinImpact/GameTask/AutoPathing/PathExecutor.cs
问题一，构建队伍问题：
avatarSideIconRectList = AutoFightAssets.Instance.AvatarSideIconRectList;
avatarIndexRectList = AutoFightAssets.Instance.AvatarIndexRectList;
以上赋值会导致avatarIndexRectList和avatarSideIconRectList的改变会直接影响改变原始参数AutoFightAssets.Instance.AvatarSideIconRectList和AutoFightAssets.Instance.AvatarIndexRectList;的值，在连续任务重会导致基准值变化，复现步骤举例为：菈乌玛队伍执行幽境JS，在进入秘境前已经进行了-14纠正，原始AutoFightAssets.Instance.AvatarIndexRectList也改变了，进入用非菈乌玛队伍，导致非菈乌玛队伍在构建队伍时机基准为已经-14纠正得值，又不进行纠正（秘境中UI恢复了），所以导致需要通过切人检测，这样会导致要通过切人检测进行纠正，但基础值错误，导致可能的多次和错误纠正次数，也可能一直错误，导致战斗卡顿。
解决方案：
1、使用NEW去赋值，保证初始值参数不变
avatarSideIconRectList = new List<Rect>(AutoFightAssets.Instance.AvatarSideIconRectList);
avatarIndexRectList = new List<Rect>(AutoFightAssets.Instance.AvatarIndexRectList);
2、在进行构建时检测上移就纠正，不上移保持不变即可。
问题二，切人修正问题： …
=> 修复菈乌玛UI问题的卡顿等问题

BetterGenshinImpact/GameTask/Model/Area/ImageRegion.cs
在PR [#2249](https://github.com/babalae/better-genshin-impact/pull/2249)中我们只修改了`Find()`，在此补充修改`FindMulti()`
=> 修复传送至渊下宫的地图时有概率识别不出来的问题 2

BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs, BetterGenshinImpact/Core/Script/Project/ScriptProject.cs, BetterGenshinImpact/GameTask/Common/Job/CountInventoryItem.cs, BetterGenshinImpact/Helpers/ScriptObjectConverter.cs, Test/BetterGenshinImpact.UnitTest/GameTaskTests/GetGridIconsTests/GridIconsAccuracyTestTaskTests.cs
#2261 
给ClearScript引擎增加集合参数解析时差点掉进反射的深坑了，，，out参数的反射让我直接放弃，，，现在就马马虎虎支持一下单层IEnumerable<T>的参数就好啦。
JS这边把返回值当字典来解析就好了，示例如下，回头更新到文档上去：
```
const result = await dispatcher.runTask(new SoloTask("CountInventoryItem", { "gridScreenName": "Food", "itemNames": ["鸡豆花", "超级至尊披萨"] }));
log.Info(`C# 方法返回鸡豆花数量: ${JSON.stringify(result["鸡豆花"])}`);
log.Info(`C# 方法返回超级至尊披萨数量: ${JSON.stringify(result["超级至尊披萨"])}`);
```
请注意目前这个方案的短处是，物品的定位效果不稳定，受背景干扰严重。请尝试自行面朝黑色场景进行降噪、多次调整视角尝试等手段
=> CountInventoryItem支持一次数多个物品

BetterGenshinImpact/Core/Script/Dependence/Dispatcher.cs, BetterGenshinImpact/Core/Script/EngineExtend.cs, BetterGenshinImpact/GameTask/AutoDomain/AutoDomainParam.cs, BetterGenshinImpact/GameTask/AutoFight/AutoFightParam.cs
简单示例
```javascript
//无参数默认使用本体的参数，但domainRoundNum=0（9999次）
let domainParam = new AutoDomainParam(); 
await dispatcher.runAutoDomainTask(domainParam);
//无参数默认使用本体的参数
let autoFightParam = new AutoFightParam();
await dispatcher.runAutoFightTask(autoFightParam);
```
秘境参数除了战斗策略需要使用`SetCombatStrategyPath()`方法、设置树脂优先列表需要使用`SetResinPriorityList()`方法，其他参数均可直接重新赋值来修改参数。 
ClearScript的` V8ScriptEngineFlags.EnableArrayConversion`不知道会不会有副作用，所以用方法来设置树脂优先列表
自动战斗参数除了战斗策略需要使用`SetCombatStrategyPath()`方法指定，其他参数均可直接重新赋值来修改参数。
```javascript
(async function () {
try {
let domainParam = new AutoDomainParam(); 
// 基础参数  
domainParam.DomainRoundNum = 1;                    // 秘境轮数,0表示9999轮  
domainParam.SetCombatStrategyPath("那钟万芙");     // 参照设置中显示的字符填写
// 队伍和秘境配置  
domainParam.PartyName = "龙王"; …
```
=> 新增自定义参数的 自动秘境 与 自动战斗 方法
